#!/usr/bin/env bash
set -e

# Install nicheformer 
pip install -e git+https://github.com/AllenNeuralDynamics/nicheformer.git@shaomai_studio#egg=nicheformer

#!/usr/bin/env bash
set -e

# check if code-server is installed, and then install extensions into specified directory
if code-server --disable-telemetry --version; then
if [ ! -d "/.vscode/extensions" ]
    then
       echo "Directory /.vscode/extensions DOES NOT exists."
       mkdir -p /.vscode/extensions/
       fi
       
       code-server --install-extension ms-python.python
       code-server --install-extension njpwerner.autodocstring
       code-server --install-extension KevinRose.vsc-python-indent
       code-server --install-extension mhutchie.git-graph
       code-server --install-extension zhuangtongfa.material-theme
       code-server --install-extension ms-python.black-formatter
	  	 code-server --install-extension ryanluker.vscode-coverage-gutters
       
       curl -L -o copilot_1.161.zip https://github.com/user-attachments/files/16859733/copilot_1.161.zip
       unzip copilot_1.161.zip
       code-server --install-extension GitHub.copilot-1.161.0.vsix
       rm copilot_1.161.zip GitHub.copilot-1.161.0.vsix
    
       else
          echo "code-server not found"
       fi